version = 1


exclude_patterns = [
    "public/**,",
    "dist/**",
    "node_modules"
]

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs","browser","mocha"]
  module_system = "commonjs"