language: node_js
node_js:
- '16'
dist: trusty
services:
- mysql
- redis-server
env:
  matrix:
  - NODE_ENV=test PORT=3000 DB_HOST=127.0.0.1 DB_DIALECT=mysql DB_PORT=3306 DB_NAME=stackoverflow_lite2 DD_ENV=ci DD_SERVICE=stack_overflow npm test REDIS_URL=redis://127.0.0.1:6379 
  global:
    secure: yfto5ksvk7m07CAj7Kt+UeCNhi8BTpjIN0/y2dje/fjy3NXiJGB2RLIzIuRIDHmLDPxAfXPTGdn8ZfCZV30BW6gvB+U9DzeQ5et9mjyIyJRHROv/R2TDZVtfWthfgtJKNBVT1KyCxX9AXSh6EpPgkAFwJomrp6hBkzJd2iEz1Nfd4ZBA/9g74sIGJoK/nXLNCbMsNudNF8uU+zKxV8PxEV000VliLWxe+ZQHLWjcF6rqUfth34qlRM6FzlW8wO7Lvg63gtQdlTPHpnMnzxpAqdPdt68CtIPgsd5x7g3wH5y5DCBktb3kgRsTuPSHxmK6rYyFHwhUBMz5riIfgKhKFGJGFfssSCgNWvGTCn1VarGX1EVwPTa0aHM/xLRb6tJffkRV2kIZyFpzIcW87vMXEl4qk48ES5Isrn7BRCIW5QJze8XZ7JTQNK9H4HpYC+iLcUilyoVbQOKWUc4Qa1Sif9q+RiXX6k1u3VB1pQBeAWCqls81i75NMtOy5QKz8+LQGgWliV4hGhzehG6teMtdz1rAAU3M/2TInR/iof257BWkFeSGPsxxFAEA/jEcR7k9yl5Cbj6pCNNZfrJ7IofHVU+Xg/qoQ4tmczPjnspH1K1LAe90DsKn8VQAgv/Rv/mjjgUwWFgMP5Irv/UJEvCsL9f4Pn0EJAFGj6qqkRVayN0=
cache:
  directories:
  - node_modules
before_install:
- mysql -u root --password="" < test/travis.sql
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
- sudo apt-get update
- sudo apt-get install gcc-4.9
- sudo apt-get upgrade libstdc++6
install:
- npm install
script:
- npm install --save sequelize
- npm install --save mysql2
- sequelize db:migrate
- nohup npm run start &
- sleep 3
- npm run test
after_success: "-npm run coverage"
