language: node_js
node_js:
- '16'
dist: focal
services:
- mysql
- redis-server
env:
  matrix:
  - NODE_ENV=test DD_ENV=ci DD_SERVICE=stack_overflow
  global:
    secure: sq4m7RrHrNG3Cg6x9Jd9SKPFzPqCgft1KFRSAbpyMqD/zmA3AVIjA0q6zHvaxb7wFnAIqc+tk9o4oZtQu7VvB7Cf851jycpCoTbj9sNdSJAaZj7qinIUrD9MJBCWvRbknwm96liKRdogDDJyNGtxGxCqaQwMHBeYdFPngfuWZVWXmlygv4CS0Yyl5rXmjlqUkOKCP3oDD5Z8XO0vJQbQ6xPpNt3oNOptJbR2nTqRYAxh5VNuLY0cO8iJ1Km58TJjHGEoK13PssOkLBYOTbfI+ypt4K5PqHfnWApGSDgOydzyqMCSHN4Key1vWvSsfW1jOCcHX3TMsm5LG5soSYsyr/HIw/amy1680iDKcQXH2PhdihEoemw0UiIEkCCutBBE/70Ko+wTYGgB3VTySvdjrDVKOEw8X8Vb/l/y2HXWTvwmpEKS5Td6RIbhCuiCAL1q71HaqLaLYm6VQTPcyc8fSxZ6OTdCstL4cpkgO6eU7jIM42GYFUPsIz5pwYInuY/nQ90JRbhCQL0mM+tzkf9sg9mMqK595z6vC9QqVE2reX8M0saaeIU7nsM8erAWbad70Qbg8Db/Tyfn61+DK+NRBJ/bQSZi/7D0NtsL91M7WlQ4XicRVDcdHM+cPx0CD9odpR3gLJL3c/JCRC3k1RvdhQcWXJXFRuMwid+UZW/jC10=
cache:
  directories:
  - node_modules
before_install:
- sudo apt-get install libstdc++6
- mysql -u root --password="" < test/travis.sql
install:
- npm install
script:
- npm install --save sequelize
- npm install --save mysql2
- sequelize db:migrate
- nohup npm run start &
- sleep 3
- npm run test
after_success: "-npm run coverage"
