language: node_js
node_js:
  - "16"
dist: trusty
services:
  - mysql
  - redis-server
env:
  - NODE_ENV=test PORT=3000
cache:
  directories:
    - node_modules
before_install:
  - mysql -u root --password="" < test/travis.sql
  
install: 
  - npm install
script:
  - sequelize db:migrate
  - nohup npm run start &
  - sleep 3
  - npm run test
after_success: 
  -npm run coverage


