language: node_js
node_js:
  - "16"
dist: trusty
services:
  - mysql
  - redis-server
env:
  - NODE_ENV=test PORT=3000
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS database_test;'
  - mysql -e 'INSERT INTO `users` (`uuid`, `id`, `username`, `password`, `first_name`, `last_name`, `phonenumber`, `email`, `role`, `stack`, `age`, `nationality`, `createdAt`, `updatedAt`, `userId`) VALUES (X'62333838346231392D353331342D346631622D616265332D326236646564616534316632', 19, 'Mocha', '$2a$10$ad1nSUmBhIm.4nTUfCIO2OUnWOmawajTOaZ2ItaxtSX3QLr9PoX1u', 'Mocha', 'Chai', 823322528, 'mocha@mochatest.com', 2, NULL, NULL, NULL, '2022-10-25 15:31:08', '2022-10-25 15:31:08', NULL);'
  
install: 
  - npm install
script:
  - sequelize db:migrate
  - sequelize db:seed:all
  - nohup npm run start &
  - sleep 3
  - npm run test
after_success: 
  -npm run coverage


