language: node_js
node_js:
- '16'
dist: focal
services:
- mysql
- redis-server
env:
  matrix:
  - NODE_ENV=test DD_ENV=ci DD_SERVICE=stack_overflow
  global:
    secure: aazC5t81K4NYbFMunqCVwVLvTr7b0aSnVxCxa/oWLbUrk5/HHJF/+bvCOUH4CI7D+nR6uQ6oJBj0qg4pedh7U5BwlAj/yEofe3b44OZVRDB2StXqHH0JSCZ1uOpaCyzLMXtSYHL4PSJdXPE3dI/K9zpTXu1FPcIc0krKCNXm+45ILusCf8OQt5xhZ9LJZI4o3ngBndy2b8gIahm9RiBZsoRTiOYu+3PNMsU6jbl4PvclgrKlqGkKpNvRtcLgTfTrEVi3lQR8XMLIi3Wn4bYliAAY3XHwIJ5T8xKlVvNC/UijIU3D2jeNYs5CcnE6MFrru1TV7yAy34CvQeBsfrfIA0vf9pCHlH6WMsaIpet9ILExIWgTx/TjcSWf7M/KJ8aLlB6ZbM+oAjP8rzN0+bRP3VhgupIkcbRKk4C5hY1ko+2XIZBREkdg1jg4C+0biP83DqRcrg7/WytpmZX6InYKUOcjFYPiqfVgKT6SWqK4p/Im7B+Z024ejw+0mgpUMTI/CFlhHOBaDGqlv4GIZlD//S7GQscNiZcLzaasd2PAOyTcAcqr48JNr8dVt0IiVe3xzeW5DRHe/aAA/49exyAG2qnhclX9pJ01mT1baCm1Ev01o7bD5kPy26XvjLLNXAVXm36gDAPhxz2pJOPv/lC3IOXDoDeMDlRCR7eWKQuIdRQ=
cache:
  directories:
  - node_modules
before_install:
- sudo apt-get install libstdc++6
- mysql -u root --password="" < test/travis.sql
install:
- npm install
script:
- npm install --save sequelize
- npm install --save mysql2
- sequelize db:migrate
- nohup npm run start &
- sleep 3
- npm run test
after_success: "-npm run coverage"
