language: node_js
node_js:
- '16'
dist: focal
services:
- mysql
- redis-server
env:
  matrix:
  - NODE_ENV=test DD_ENV=ci DD_SERVICE=stack_overflow
  global:
    secure: GQzr0jAl9QA0yvsCMVg75b/EbpT7G/C3msSOAWfbQTxDTxoOoHMMXFlaW5h4gL70DhTZ2EtvLzOkyhNhFF4GfYHNttFGhQJ8Y2cVo9Wr+kk8wLWSIhqC89j0k6k/WO2a32VaSH4dIyukovS/5+bTyoCRXNKXTlODkqVWc4SxjiUNzLJx+UGYOs2cpKBQfmnXOzmLRQoGFYVSya333YrEZPHEnp8+fjT0JyWYN4Q0p3Wt8oZa6w5xUao8c2P+J/aJOU2vMwYmVoVqjWqBroRqrWrOz7l041OG8iyQkxf/blQZMCWJsIHmHWYyDReB0EJabaf4+NK2bWIAuqEKWWyW9sQM1LQgBPbIL04HquSzuawhqw4vFI/9hvYpcUl5iXlynpZoqTNlBmN3TEbR4XKj+L6Rf0hyuIf7Qn77UiDkqvSYZ9sRTMJ3/LEfd6fUX01c8fJJ4zBYQYgBuruo7q1JE1akmDLcEJmhNe8KYjXfzv4EXsGbPeuFvSe88/pcKUKqqAg/mujnfB9DYaxnD3tfn/w4/a7q6zMvsZEOX1eIytCbS3tN3FeLTyov5dMRnfInmNIcQrTgjat+OxCmRNULuTaT74E/4CsRJkH9cr6nERs8uDI8fnzYRe1Wr/WL2gz0EJt3WkkaTo36l0T0p/M5Gy6DgexZa3+A8lZPs6eciDk=
cache:
  directories:
  - node_modules
before_install:
- sudo apt-get install libstdc++6
- mysql -u root --password="" < test/travis.sql
install:
- npm install
script:
- npm install --save sequelize
- npm install --save mysql2
- sequelize db:migrate
- nohup npm run start &
- sleep 3
- npm run test
after_success: "-npm run coverage"
