name: MySQL, Redis, and Sequelize Workflow

on:
  pull_request:
    branches:
      - dev

env:
  NODE_ENV: test
  DD_ENV: ci
  DD_SERVICE: stack_overflow

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variables
      env:
        NODE_ENV: ${{ env.NODE_ENV }}
        DD_ENV: ${{ env.DD_ENV }}
        DD_SERVICE: ${{ env.DD_SERVICE }}

    - name: Set up MySQL client
      uses: mysql/mysql-docker-action@v1
    
    - name: Create database and import test data
      run: |
        mysql -u root --password="" < test/travis.sql

    - name: Set up Redis client
      uses: redis/redis-action@v1

    - name: Install dependencies
      run: |
        npm install --save sequelize
        npm install --save mysql2

    - name: Run migrations
      run: npx sequelize db:migrate

  test:
    runs-on: ubuntu-latest
    needs: setup-mysql
    steps:

    - name: Run tests
      run: |
        nohup npm run start &
        sleep 3
        npm run test
        npm run coverage

