name: Node.js Workflow

on:
  pull_request:
    branches:
      - dev
      - main

env:
  NODE_ENV: test
  DD_ENV: ci
  DD_SERVICE: stack_overflow
  MYSQL_ROOT_PASSWORD: password

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set environment variables
      env:
        NODE_ENV: ${{ env.NODE_ENV }}
        DD_ENV: ${{ env.DD_ENV }}
        DD_SERVICE: ${{ env.DD_SERVICE }}
      run: |
        echo "NODE_ENV=${NODE_ENV}" >> $GITHUB_ENV
        echo "DD_ENV=${DD_ENV}" >> $GITHUB_ENV
        echo "DD_SERVICE=${DD_SERVICE}" >> $GITHUB_ENV

    - name: Set up MySQL
      run: |
        sudo apt install mysql-server mysql-client
        sudo systemctl restart mysql

    - name: Import test data
      run: |
        sudo mysql -u root < .github/workflows/travis.sql

    - name: Set up Redis
      run: sudo apt-get install redis-server

    - name: Install dependencies
      run: |
        npm install
        npm install --save sequelize
        npm install --save mysql2

    - name: Run migrations
      run: npx sequelize db:migrate

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:

    - name: Run tests
      run: |
        nohup npm run start &
        sleep 3
        npm run test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Report coverage
      run: npm run coverage
