# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create env file
      run: |
        touch .env
        echo NODE_ENV=test  >> .env
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install npm latest
      run: |
         npm i -g npm@latest
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    - name: run test
      env :
        PORT : 3535
        DB_USERNAME : root
        DB_PASSWORD : Hibrahim00..
        DB_HOST : 127.0.0.1
        DB_DIALECT : mysql
        DB_PORT : 3306
        DB_NAME : stackoverflow_lite2
        JWT_SECRET : stackoverflow
        JWT_EXPIRES : 10m
        JWT_COOKIE_EXPIRES_IN : 10
        BCRYPT_STRING : stackoverflow
        REDIS_URL : redis://127.0.0.1:6379
        AI_KEY : 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
        AI_ORG : org-jZ1NQsXwnYa8b8C65gYWBoXn
        AI_UUID : 2bdda0e4-a65e-47d9-8085-d06a0da5d51c
        HONEYBADGER_KEY : hbp_i3Qh3i4OYpEd6IFpwRkmogiRWlg5EU20NxXQ
        CODECOV_TOKEN : 9798862f-19e2-477a-b975-748fe1b5a9b7
        SENTRY_URL : https://88e74b1f40984253adfb9bbb6e4c820d@o4504617178038272.ingest.sentry.io/4504617179152384
        DD_CIVISIBILITY_AGENTLESS_ENABLED : true
        DD_API_KEY : 8cfab4e9c1dbb2f91be2af5d82d65375
        DD_SITE : us5.datadoghq.com
        DD_ENV : ci
        DD_SERVICE : stack_overflow npm test
        DD_APP_KEY : 3cc0bdc127499ddc165963d60371e8a60ac6fc32
      run: |
        nohup npm run start &
        sleep 3
        npm run test

