name: Node.js Workflow

on:
  pull_request:
    branches:
      - dev
      - main

env:
  NODE_ENV: test_github_actions
  DD_ENV: ci
  DD_SERVICE: stack_overflow
  MYSQL_ROOT_PASSWORD: password

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          # MYSQL_DATABASE: test
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set environment variables
      env:
        NODE_ENV: ${{ env.NODE_ENV }}
        DD_ENV: ${{ env.DD_ENV }}
        DD_SERVICE: ${{ env.DD_SERVICE }}
      run: |
        sudo /etc/init.d/mysql start
        echo "NODE_ENV=${NODE_ENV}" >> $GITHUB_ENV
        echo "DD_ENV=${DD_ENV}" >> $GITHUB_ENV
        echo "DD_SERVICE=${DD_SERVICE}" >> $GITHUB_ENV

    - name: Import test data
      env:
        MYSQL_PWD: ${{ env.MYSQL_ROOT_PASSWORD }}
      run: |
        mysql -h 127.0.0.1 --port 8888 -u root -ppassword < test/travis.sql

    - name: Set up Redis
      run: sudo apt-get install redis-server

    - name: Install dependencies
      run: |
        npm install
        npm install --save sequelize
        npm install --save mysql2
        nohup npm run start &
        sleep 3
        npm run test

    - name: Run migrations
      run: npx sequelize db:migrate

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:

    - name: Run tests
      run: |
        nohup npm run start &
        sleep 3
        npm run test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Report coverage
      run: npm run coverage
# ///